package com.aqms.sensordataservice.model;

import java.math.BigDecimal;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.aqms.sensordataservice.FileUtil;

import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

//POJO of the Sensor Stream/ Data
@Data
@AllArgsConstructor
@NoArgsConstructor
@ToString
@Builder
//Annotation to specify the table name in the DynamoDB
@DynamoDBTable(tableName = "SensorData")
public class SensorData {
//Annotation for hash key for the table in DynamoDB
	@DynamoDBHashKey(attributeName = "dataId")
//Annotation for auto-generated key for the table in DynamoDB
	@DynamoDBAutoGeneratedKey
	private String dataId;

	// Annotation for attribute in the table in DynamoDB
	@DynamoDBAttribute
	private String sensorid;

	// Annotation for attribute in the table in DynamoDB with validation using
	// @DecimalMin and @DecimalMax
	@DynamoDBAttribute
	@DecimalMin(value = FileUtil.minO2)
	@DecimalMax(value = FileUtil.maxO2)
	private BigDecimal o2;

	// Annotation for attribute in the table in DynamoDB with validation using
	// @DecimalMin and @DecimalMax
	@DynamoDBAttribute
	@DecimalMin(value = FileUtil.minCO2)
	@DecimalMax(value = FileUtil.maxCO2)
	private BigDecimal co2;

	// Annotation for attribute in the table in DynamoDB with validation using
	// @DecimalMin and @DecimalMax
	@DynamoDBAttribute
	@DecimalMin(value = FileUtil.minSO2)
	@DecimalMax(value = FileUtil.maxSO2)
	private BigDecimal so2;

	// Annotation for attribute in the table in DynamoDB with validation using
	// @DecimalMin and @DecimalMax
	@DynamoDBAttribute
	@DecimalMin(value = FileUtil.minCO)
	@DecimalMax(value = FileUtil.maxCO)
	private BigDecimal co;

	// Annotation for attribute in the table in DynamoDB with validation using
	// @DecimalMin and @DecimalMax
	@DynamoDBAttribute
	@DecimalMin(value = FileUtil.minC)
	@DecimalMax(value = FileUtil.maxC)
	private BigDecimal c;

	// Annotation for attribute in the table in DynamoDB
	@DynamoDBAttribute
	private BigDecimal safeValue;

	// Annotation for attribute in the table in DynamoDB
	@DynamoDBAttribute
	private Boolean safety;

}
